--база HIVTest
 --CREATE TABLE DEPARTMENTS
 --(
 --  DEPT_ID INT PRIMARY KEY,
 --  DEPT_NAME VARCHAR(50)
 --);
--insert into DEPARTMENTS values (10, 'ADMIN');
--insert into DEPARTMENTS values (20, 'BILLING');

 --CREATE TABLE EMPLOYEES
 --(
 --  EMP_ID INT PRIMARY KEY,
 --  EMP_NAME VARCHAR(50),
 --  EMP_DEPT INT REFERENCES DEPARTMENTS(DEPT_ID),
 --  EMP_SALARY DECIMAL(10,2)
 --);
--insert into EMPLOYEES values (1, 'AARON', 10, 100);
--insert into EMPLOYEES values (2, 'GRAHAM', 20, 400);

UPDATE DEPARTMENTS Set DEPT_NAME="ADMINISTRATION" Where (DEPT_ID=10);

UPDATE EMPLOYEES
SET EMP_SALARY = EMP_SALARY * 1.5
WHERE EMP_SALARY < (SELECT MAX(EMP_SALARY) FROM EMPLOYEES);

UPDATE EMPLOYEES
SET EMP_SALARY = EMP_SALARY + 500
WHERE EMP_DEPT <> 10;

UPDATE EMPLOYEES
SET EMP_SALARY = 1200
WHERE EMP_SALARY < (SELECT AVG(EMP_SALARY) FROM EMPLOYEES);

select *
from EMPLOYEES;

--select *
--from DEPARTMENTS t1
--inner join EMPLOYEES t2
--on t1.DEPT_ID = t2.EMP_DEPT;

--SELECT EMP_ID, EMP_NAME, EMP_DEPT,
--       CASE WHEN EMP_SALARY = (SELECT MIN(EMP_SALARY) FROM EMPLOYEES)
--            THEN EMP_SALARY * 1.5
--            ELSE EMP_SALARY
--       END AS EMP_SALARY
--FROM EMPLOYEES;

--UPDATE EMPLOYEES
--SET EMP_SALARY = 150
--WHERE EMP_DEPT = 10;
--UPDATE EMPLOYEES
--SET EMP_SALARY = 900
--WHERE EMP_DEPT = 20;