--база HIVTest
--CREATE TABLE BANKS (
--BNK_ID INTEGER,
--BNK_NAME VARCHAR(50),
--BNK_COUNTRY VARCHAR(50),
--BNK_SWIFTCODE VARCHAR(11)
--);
--insert into BANKS values (1, 'WFB BANK, INC.', 'United States', null);
--insert into BANKS values (2, 'H.D.F.C.', 'India', null);

--CREATE TABLE SWIFTCODES (
--SC_ID INTEGER PRIMARY KEY,
--SC_BANKID INTEGER REFERENCES BANKS(BNK_ID),
--SC_CODE VARCHAR(11)
--);
--insert into SWIFTCODES values (1, 1, 'FDACPREFM');
--insert into SWIFTCODES values (2, 2, 'ASDFAGYT');

select *
from BANKS;

UPDATE BANKS
SET BNK_COUNTRY = upper(BNK_COUNTRY);
--select BNK_ID, BNK_NAME, upper(BNK_COUNTRY) AS BNK_COUNTRY, BNK_SWIFTCODE from BANKS;

UPDATE BANKS
SET BNK_NAME = REPLACE(REPLACE(BNK_NAME, '.', ''), ',', '');
--SELECT BNK_ID, REPLACE(REPLACE(BNK_NAME, '.', ''), ',', '') AS BNK_NAME, BNK_COUNTRY, BNK_SWIFTCODE FROM BANKS;

--SELECT *
--FROM BANKS T1
--INNER JOIN SWIFTCODES T2
--ON T1.BNK_ID = T2.SC_BANKID;

UPDATE BANKS
SET BNK_SWIFTCODE = SC_CODE
FROM BANKS
INNER JOIN SWIFTCODES
ON BNK_ID = SC_BANKID;